# Generated by Django 4.2.5 on 2023-09-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigne',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
