# Generated by Django 4.2.5 on 2023-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enseigne_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='email',
        ),
        migrations.AddField(
            model_name='ecole',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domaine',
            name='image',
            field=models.URLField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='image',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='metier',
            name='image',
            field=models.URLField(max_length=10000),
        ),
    ]
