# Generated by Django 4.2.5 on 2024-07-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_domaine_img_rename_nom_domaine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseigne',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='enseigne',
            name='name',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.RenameField(
            model_name='metier',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='metier',
            old_name='salaire',
            new_name='fee',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='img',
        ),
        migrations.RemoveField(
            model_name='domaine',
            name='matieres_principales',
        ),
        migrations.AddField(
            model_name='domaine',
            name='fee',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='domaine',
            name='year',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ecole',
            name='departments',
            field=models.ManyToManyField(to='api.domaine'),
        ),
        migrations.AddField(
            model_name='metier',
            name='departments',
            field=models.ManyToManyField(to='api.domaine'),
        ),
        migrations.AddField(
            model_name='metier',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='question',
            name='domaines',
            field=models.ManyToManyField(to='api.domaine'),
        ),
        migrations.DeleteModel(
            name='Enseigne',
        ),
    ]
